### ISSUE TITLE
Deprecation warning fix for serverless 3.0.0

### ISSUE THREAD

**Issue by gghukasyan** [AntonBazhal/serverless-plugin-custom-roles#18]
Right now with serverless 2 we're getting the following warning
Deprecation warning: Starting with version 3.0.0, following property will be replaced:
              "provider.iamRoleStatements" -> "provider.iam.role.statements"
Plugin needs to add support for provider.iam.role.statements

**Comment by AntonBazhal** [comment]
Duplicate of #16
