### ISSUE TITLE
Doesn't add AWSLambdaVPCAccessExecutionRole when VPC is enabled.

### ISSUE THREAD

**Issue by thejuan** [AntonBazhal/serverless-plugin-custom-roles#3]
I'm using VPC and when I add this plugin my deploy fails as its missing the AWSLambdaVPCAccessExecutionRole.

I've also tried to add this via
iamManagedPolicies:
    - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

**Comment by paquiro** [comment]
> I'm using VPC and when I add this plugin my deploy fails as its missing the AWSLambdaVPCAccessExecutionRole.
> 
> I've also tried to add this via
> iamManagedPolicies:
> - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole

How did you resolve it?

**Comment by AntonBazhal** [comment]
I'll take a look at this in the next few days.

**Comment by AntonBazhal** [comment]
@paquiro This is fixed now, but I'd like to make some more changes before releasing v2.0.0.

**Comment by AntonBazhal** [comment]
Released now
